<%-- 机场管理页面 --%>
<%@ Page Title="机场管理 - 纸飞机航空公司" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" ErrorPage="~/Others/Error.aspx"
    CodeBehind="AirportAdmin.aspx.cs" Inherits="HHUAir.Admin.AirportAdmin" ErrorPage="~/Error.aspx" %>

<asp:Content ID="HeaderContent" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
    </style>
</asp:Content>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <%-- 数据源控件，提供对Airports数据表的检索和增删改支持 --%>
    <asp:SqlDataSource ID="SqlDataSourceAirports" runat="server" ConnectionString="<%$ ConnectionStrings:ApplicationServices %>"
        SelectCommand="SELECT * FROM [Airports]" UpdateCommand="UPDATE [Airports]
                       SET Name = @Name, City = @City, IsRecommend = @IsRecommend
                       WHERE Name = @original_Name AND City = @original_City" DeleteCommand="DELETE FROM [Airports] WHERE Name = @original_Name"
        InsertCommand="INSERT INTO [Airports](Name, City, IsRecommend) VALUES (@Name, @City, @IsRecommend)"
        OldValuesParameterFormatString="original_{0}"></asp:SqlDataSource>
    <p>
        欢迎进入机型管理！
    </p>
    <p>
        您可以在此管理纸飞机航空公司航班涉及的所有机场信息，或者<a href="AdminHome.aspx" title="">返回机票管理系统首页</a>。
    </p>
    <p>
        <asp:Label ID="LabelErrorMessage" runat="server" ForeColor="Red" Text="[ERROR]" 
            Visible="False"></asp:Label>
    </p>
    <table align="center" cellpadding="10">
        <tr>
            <td style="background-color: #F7F6F3;">
                <%-- 增加机场，通过将各控件绑定到数据表各字段实现 --%>
                <asp:DetailsView ID="DetailsViewNewAirport" runat="server" Height="50px" Width="220px"
                    AllowPaging="True" AutoGenerateInsertButton="True" 
                    AutoGenerateRows="False" Caption="添加新机场"
                    CellPadding="4" DataSourceID="SqlDataSourceAirports" DefaultMode="Insert" ForeColor="#333333"
                    GridLines="None" oniteminserting="DetailsViewNewAirport_ItemInserting" 
                    onitemcommand="DetailsViewNewAirport_ItemCommand">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
                    <EditRowStyle BackColor="#999999" />
                    <FieldHeaderStyle BackColor="#F7F6F3" Font-Bold="True" />
                    <Fields>
                        <asp:BoundField DataField="Name" HeaderText="机场名称" >
                        <HeaderStyle Width="100px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="City" HeaderText="所在城市" >
                        <HeaderStyle Width="100px" />
                        </asp:BoundField>
                        <asp:CheckBoxField DataField="IsRecommend" HeaderText="推荐" >
                        <HeaderStyle Width="100px" />
                        </asp:CheckBoxField>
                    </Fields>
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                </asp:DetailsView>
            </td>
            <td align="center">
                <%-- 显示现有机场，并提供编辑和删除记录的功能，通过将各控件绑定到数据表各字段实现 --%>
                <asp:GridView DataKeyNames="Name,City" ID="GridViewAirports" runat="server" DataSourceID="SqlDataSourceAirports"
                    AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" Caption="现有机场" CellPadding="4" ForeColor="#333333"
                    GridLines="None" Style="text-align: center" 
                    onrowupdating="GridViewAirports_RowUpdating" 
                    onrowcancelingedit="GridViewAirports_RowCancelingEdit">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="机场名称" SortExpression="Name">
                            <HeaderStyle Width="150px" />
                            <ItemStyle Width="150px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="City" HeaderText="所在城市" SortExpression="City">
                            <HeaderStyle Width="150px" />
                            <ItemStyle Width="150px" />
                        </asp:BoundField>
                        <asp:CheckBoxField DataField="IsRecommend" HeaderText="推荐" 
                            SortExpression="IsRecommend">
                            <HeaderStyle Width="50px" Wrap="False" />
                            <ItemStyle Width="50px" />
                        </asp:CheckBoxField>
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                    <EmptyDataTemplate>
                        尚未添加任何机场
                    </EmptyDataTemplate>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>
