<%-- 机型管理页面 --%>
<%@ Page Title="机型管理 - 纸飞机航空公司" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" ErrorPage="~/Others/Error.aspx"
    CodeBehind="ModelAdmin.aspx.cs" Inherits="HHUAir.Admin.ModelAdmin" ErrorPage="~/Error.aspx" %>

<asp:Content ID="HeaderContent" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
    </style>
</asp:Content>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <%-- 数据源控件，提供对Models数据表的检索和增删改支持 --%>
    <asp:SqlDataSource ID="SqlDataSourceModels" runat="server" ConnectionString="<%$ ConnectionStrings:ApplicationServices %>"
        SelectCommand="SELECT * FROM [Models]" UpdateCommand="UPDATE [Models]
                       SET Name = @Name, Type = @Type, MaxSeats = @MaxSeats, MinSeats=@MinSeats
                       WHERE Name = @original_Name" DeleteCommand="DELETE FROM [Models] WHERE Name = @original_Name"
        InsertCommand="INSERT INTO [Models](Name, Type, MinSeats, MaxSeats) VALUES (@Name, @Type, @MinSeats, @MaxSeats)"
        OldValuesParameterFormatString="original_{0}"></asp:SqlDataSource>
    <p>
        欢迎进入机型管理！
    </p>
    <p>
        您可以在此管理纸飞机航空公司所有飞机型号及相关资料，或者<a href="AdminHome.aspx" title="">返回机票管理系统首页</a>。
    </p>
    <p>
        <asp:Label ID="LabelErrorMessage" runat="server" ForeColor="Red" Text="[ERROR]" 
            Visible="False"></asp:Label>
    </p>
    <table align="center" cellpadding="10">
        <tr>
            <td style="background-color: #F7F6F3;">
                <%-- 增加机型，通过将各控件绑定到数据表各字段实现 --%>
                <asp:DetailsView ID="DetailsViewNewModel" runat="server" Height="50px" Width="220px"
                    AllowPaging="True" AutoGenerateInsertButton="True" 
                    AutoGenerateRows="False" Caption="添加新机型"
                    CellPadding="4" DataSourceID="SqlDataSourceModels" DefaultMode="Insert" ForeColor="#333333"
                    GridLines="None" onitemcommand="DetailsViewNewModel_ItemCommand" 
                    oniteminserting="DetailsViewNewModel_ItemInserting">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
                    <EditRowStyle BackColor="#999999" />
                    <FieldHeaderStyle BackColor="#F7F6F3" Font-Bold="True" />
                    <Fields>
                        <asp:BoundField DataField="Name" HeaderText="机型名称">
                        <HeaderStyle Width="100px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="Type" HeaderText="所属类型">
                        <HeaderStyle Width="100px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="MaxSeats" HeaderText="最多座位数">
                        <HeaderStyle Width="100px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="MinSeats" HeaderText="最少座位数">
                        <HeaderStyle Width="100px" />
                        </asp:BoundField>
                        <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
                    </Fields>
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                </asp:DetailsView>
            </td>
            <td align="center">
                <%-- 显示现有机型，并提供编辑和删除记录的功能，通过将各控件绑定到数据表各字段实现 --%>
                <asp:GridView DataKeyNames="Name" ID="GridViewModels" runat="server" DataSourceID="SqlDataSourceModels"
                    AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" Caption="现有机型" CellPadding="4" ForeColor="#333333"
                    GridLines="None" Style="text-align: center" 
                    onrowcancelingedit="GridViewModels_RowCancelingEdit" 
                    onrowupdating="GridViewModels_RowUpdating">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="机型名称" SortExpression="Name">
                            <HeaderStyle Width="150px" />
                            <ItemStyle Width="150px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="Type" HeaderText="所属类型" SortExpression="Type">
                            <HeaderStyle Width="150px" />
                            <ItemStyle Width="150px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="MaxSeats" HeaderText="最多座位数" SortExpression="MaxSeats DESC">
                            <HeaderStyle Width="100px" />
                            <ItemStyle Width="100px" />
                        </asp:BoundField>
                        <asp:BoundField DataField="MinSeats" HeaderText="最少座位数" SortExpression="MinSeats">
                            <HeaderStyle Width="100px" />
                            <ItemStyle Width="100px" />
                        </asp:BoundField>
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                    <EmptyDataTemplate>
                        尚未添加任何机型
                    </EmptyDataTemplate>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>
